---
- name: Enable nginx service
  become: yes
  hosts: webserver
  tasks:

    - name: Install Nginx
      apt:
        name: nginx-extras
        update-cache: yes

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

    - name: Replace default web page
      copy: 
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
    
    #- name: Update nginx config
    #  copy: 
    #    src: nginx.conf 
    #    dest: /etc/nginx/sites-enabled/default
    #    mode: 0644  
    #  notify: restart nginx

  handlers:
    - name: restart nginx
      debug:
        msg: checking config first
      changed_when: true
      notify:
        - check nginx configuration
        - restart nginx - after config check
    
    - name: check nginx configuration
      command: nginx -t
      register: nginx_test_result
      changed_when: nginx_test_result.rc != 0        

    - name: restart nginx - after config check
      systemd:
        daemon_reload: true
        name: nginx
        state: restarted
      register: restart_nginx_result
      ignore_errors: true
      notify: check status nginx
    
    - name: check status nginx
      fail:
        msg: "Staring nginx failed: 
        {{ restart_nginx_result.status.StandardError }}
        {{ restart_nginx_result.status.StandardOutput }}"
      when: restart_nginx_result.failed
    
